// login
export const LOGIN = {
    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILURE: 'LOGIN_FAILURE',
};

export const LOGOUT = 'LOGOUT';

export const DATA_BY_SOURCE = {
    DATA_BY_SOURCE_REQUEST: 'DATA_BY_SOURCE_REQUEST',
    DATA_BY_SOURCE_SUCCESS: 'DATA_BY_SOURCE_SUCCESS',
    DATA_BY_SOURCE_FAILURE: 'DATA_BY_SOURCE_FAILURE',
};

export const DATA_FEED_ADD = {
    DATA_FEED_ADD_REQUEST: 'DATA_FEED_ADD_REQUEST',
    DATA_FEED_ADD_SUCCESS: 'DATA_FEED_ADD_SUCCESS',
    DATA_FEED_ADD_FAILURE: 'DATA_FEED_ADD_FAILURE',
};

export const DATA_FEED_REMOVE = {
    DATA_FEED_REMOVE_REQUEST: 'DATA_FEED_REMOVE_REQUEST',
    DATA_FEED_REMOVE_SUCCESS: 'DATA_FEED_REMOVE_SUCCESS',
    DATA_FEED_REMOVE_FAILURE: 'DATA_FEED_REMOVE_FAILURE',
};

// data
export const DATA_SOURCES = {
    DATA_SOURCES_REQUEST: 'DATA_SOURCES_REQUEST',
    DATA_SOURCES_SUCCESS: 'DATA_SOURCES_SUCCESS',
    DATA_SOURCES_FAILURE: 'DATA_SOURCES_FAILURE',
};


// notification
export const NOTIFICATION = {
    NOTIFICATION_SUCCESS: 'NOTIFICATION_SUCCESS',
    NOTIFICATION_ERROR: 'NOTIFICATION_ERROR',
    NOTIFICATION_CLEAR: 'NOTIFICATION_CLEAR',
};
